/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SobreNosotrosIndexImport } from './routes/sobre-nosotros/index'
import { Route as ProductosIndexImport } from './routes/productos/index'
import { Route as PersonalizarIndexImport } from './routes/personalizar/index'
import { Route as ClubIndexImport } from './routes/club/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SobreNosotrosIndexRoute = SobreNosotrosIndexImport.update({
  path: '/sobre-nosotros/',
  getParentRoute: () => rootRoute,
} as any)

const ProductosIndexRoute = ProductosIndexImport.update({
  path: '/productos/',
  getParentRoute: () => rootRoute,
} as any)

const PersonalizarIndexRoute = PersonalizarIndexImport.update({
  path: '/personalizar/',
  getParentRoute: () => rootRoute,
} as any)

const ClubIndexRoute = ClubIndexImport.update({
  path: '/club/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/club/': {
      id: '/club/'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubIndexImport
      parentRoute: typeof rootRoute
    }
    '/personalizar/': {
      id: '/personalizar/'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof PersonalizarIndexImport
      parentRoute: typeof rootRoute
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosIndexImport
      parentRoute: typeof rootRoute
    }
    '/sobre-nosotros/': {
      id: '/sobre-nosotros/'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ClubIndexRoute,
  PersonalizarIndexRoute,
  ProductosIndexRoute,
  SobreNosotrosIndexRoute,
})

/* prettier-ignore-end */
